# Generated by Django 4.2.4 on 2023-08-26 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0002_alter_task_completed_alter_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('completed', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager_app.registration')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
