# Generated by Django 4.2.4 on 2023-08-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0003_task_manage_delete_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_manage',
            old_name='email',
            new_name='user',
        ),
    ]
